In [1]:
import torch

In [3]:
@torch.no_grad()
def fun_a(t):
    return t*2

In [4]:
def fun_b(t):
    return t*2

In [5]:
t = torch.ones(3, requires_grad = True)

In [6]:
t

tensor([1., 1., 1.], requires_grad=True)

In [7]:
a = fun_a(t)
b = fun_b(t)

In [9]:
a

tensor([2., 2., 2.])

In [10]:
b

tensor([2., 2., 2.], grad_fn=<MulBackward0>)

In [11]:
a*t

tensor([2., 2., 2.], grad_fn=<MulBackward0>)

In [12]:
with torch.no_grad():
    c = t*2

In [13]:
c

tensor([2., 2., 2.])